### ISSUE TITLE
There is no such function: cache expiration triggers callback method

### ISSUE THREAD

**Issue by leeyisoft** [zotonic/depcache#18]
There is no such function: cache expiration triggers callback method

```
Key = "dniddddd".
Data = <<"dddddddddddd">>.
MaxAge = 5.
ExpirationCallbackFun = fun() -> 
    Data = depcache:get(Key),
    io:format("fun: ~p~n", [Data]),
    Do something else
end.
depcache:set(Key, Data, MaxAge, ExpirationCallbackFun).
```

**Comment by mworrell** [comment]
I think for this we would use the memo function.

Fetch the data, and if not present (or expired) call the function, store the result and return the result.

**Comment by leeyisoft** [comment]
> I think for this we would use the memo function.
> 
> Fetch the data, and if not present (or expired) call the function, store the result and return the result.

What I want is the ability to delay messages:

Delivers a message to the peer end. If it receives an acknowledgement from the peer end within 3 seconds, the message is deleted from the cache.

If it is not received within 3 seconds, it will be delivered again and checked after 5 seconds

**Comment by arjan** [comment]
I think a feature request like this is beyond the scope of this library, you can implement it yourself by using `erlang:send_after/3` to send a message to yourself at the moment of expiration and act on it.

**Comment by leeyisoft** [comment]
> I think a feature request like this is beyond the scope of this library, you can implement it yourself by using `erlang:send_after/3` to send a message to yourself at the moment of expiration and act on it.

This simple method is what I need. I thought this problem was complicated before I saw your reply. 
I really appreciate your reply!
