### ISSUE TITLE
Fix deprecations

### ISSUE THREAD

**Issue by ddeboer** [zotonic/depcache#2]
On the Zotonic Travis builds (Erlang 19) we get:

```
/home/travis/build/zotonic/zotonic/deps/depcache/src/depcache.erl:693: Warning: erlang:now/0: Deprecated BIF. See the "Time and Time Correction in Erlang" chapter of the ERTS User's Guide for more information.
/home/travis/build/zotonic/zotonic/deps/depcache/src/depcache.erl:694: Warning: random:seed/3: the 'random' module is deprecated; use the 'rand' module instead
/home/travis/build/zotonic/zotonic/deps/depcache/src/depcache.erl:753: Warning: random:uniform/1: the 'random' module is deprecated; use the 'rand' module instead
```

**Comment by mworrell** [comment]
In https://github.com/zotonic/depcache/pull/4/files#diff-e89b527335efc9f7f45ddb9a2294e3b3R791 we replaced the `random:uniform/1` call with `rand:uniform/1`.

The call now `now/1` and `random:seed/3` has also been removed.

This change makes depcache incompatible with R16B03-1
I think we need to add a minimum Erlang version to the *rebar config* file.

When was `rand` introduced?  In 17?

**Comment by ddeboer** [comment]
Good point.

> When was rand introduced? In 17?

Wow, that‘s actually quite hard to find. First look for stdlib: 2.5 [introduced rand](http://erlang.org/doc/apps/stdlib/notes.html#id85256) with number `OTP-12586`. Googling for that you find it in [OTP 18](http://erlang.org/download/otp_src_18.0.readme).

Let’s wrap the new `rand` in an `erlang:is_builtin`, so we don’t yet have to drop pre R18 support.

**Comment by arjan** [comment]
Deprecating OTP < 18 seems reasonable to me.

**Comment by ddeboer** [comment]
Deprecating is something else than removing support for it. :wink:

On master, of course, we already require 18. The same *could* be done on 0.x (and would be okay with us, as we’re running 18 or higher anyway), but I’m guessing it will hurt some of Zotonic’s users.

**Comment by mworrell** [comment]
It compiles cleanly on 19, closing this issue.
