### ISSUE TITLE
Bad match in memo/

### ISSUE THREAD

**Issue by mgpld** [zotonic/depcache#5]
Hello,

Problems with the following depcache.erl code: (line 120)

                   case F of
                         {M,F,A} -> erlang:apply(M,F,A);

**F could not match...**

The patch is here:
[depcache.txt](https://github.com/zotonic/depcache/files/3176250/depcache.txt)

Thank you for this module !

**Comment by arjan** [comment]
Yes you're right, that looks like a valid patch. Could you send a PR, to make our lives easier? :-)

**Comment by mworrell** [comment]
Thanks!

I applied your patch and also cleaned up some specs and other function args.
